version: '3.8'

services:
  db:
    container_name: db-escuela-conductores
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Cd1526a2a8
    ports:
      - "1433:1433"
    volumes:
      - db-escuela-conductores:/var/opt/mssql
    
volumes:
  db-escuela-conductores: