spring:
  application:
    name: entities
  profiles:
    active:
    - dev
  
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=bdescuelaconductores;encrypt=true;trustServerCertificate=true
    username: sa
    password: Cd1526a2a8
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 4001

