
spring:
  application:
    name: entities
  profiles:
    active:
    - dev
  
  datasource:
    # url: jdbc:sqlserver://localhost:1433;databaseName=BD_SIRIM;encrypt=true;trustServerCertificate=true
    url: jdbc:sqlserver://172.27.0.124;databaseName=BD_SIRIM;encrypt=true;trustServerCertificate=true
    username: userestadistica
    password: $Us3R_3sT4d1sTic4$
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver



  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 4003


